(set-logic LIA)
(synth-fun f0 ((x0 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x0 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var i Int)
(declare-var i0 Int)
(declare-var i3 Int)
(declare-var i4 Int)
(constraint (or (not (and (and (>= i3 0) (>= i4 0)) (< i0 2))) (= (+ (+ 1 i3) i4) (f0 i))))
(check-synth)
