(set-logic LIA)
(synth-fun join ((x Int) (x0 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x x0 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var i0 Int)
(constraint (= i0 (join 0 i0)))
(check-synth)
