(set-logic LIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(synth-fun f0 ((x Int) (x0 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x x0 (- Ix) (+ Ix Ix) (max Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var i Int)
(declare-var i0 Int)
(declare-var i1 Int)
(constraint (= (+ 1 (max i0 i1)) (+ i (f0 i i0))))
(check-synth)
