(set-logic LIA)
(synth-fun f2 ((x0 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x0 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun f1 ((x1 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x1 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun join ((x2 Int) (x3 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x2 x3 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var i Int)
(declare-var i0 Int)
(constraint (= i0 (join (f1 0) (f2 i0))))
(constraint (= (+ i i0) (join (f1 (+ i 0)) (f2 i0))))
(check-synth)
