(set-logic LIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(synth-fun join2 ((x10 Int) (x11 Int) (x12 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x10 x11 x12 (- Ix) (+ Ix Ix) (max Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var p3 Int)
(declare-var i4 Int)
(declare-var i6 Int)
(constraint (= (max p (max p3 i4)) (max p (join2 p3 i4 i6))))
(check-synth)
