(set-logic LIA)
(synth-fun sub1 ((x11 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x11 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun add1 ((x12 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x12 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun add ((x13 Int) (x14 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x13 x14 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun c0 () Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(constraint (= 0 (add c0 c0)))
(constraint (= 1 (add (add1 c0) c0)))
(constraint (= 1 (add c0 (add1 c0))))
(constraint (= (- 1) (add c0 (sub1 c0))))
(check-synth)
