(set-logic LIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(synth-fun join2 ((x10 Int) (x11 Int) (x12 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x10 x11 x12 (- Ix) (+ Ix Ix) (max Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var p7 Int)
(declare-var i0 Int)
(declare-var i2 Int)
(constraint (= (max p i2) (max p (join2 p7 i0 i2))))
(check-synth)
