(set-logic DTLIA)
(synth-fun oplus0 ((x Int) (x0 (Tuple Int Int Int))) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x ((_ tupSel 0) x0) ((_ tupSel 1) x0) ((_ tupSel 2) x0) (- Ix) (+ Ix Ix)))
  (Ic Int ((Constant Int)))))
(declare-var p Int)
(constraint (= p (oplus0 p (mkTuple 0 0 0))))
(check-synth)
