(set-logic LIA)
(synth-fun c0 ((x5 Int) (x6 Int)) Bool ((Ipred Bool) (Ix Int) (Ic Int))
 ((Ipred Bool ((not Ipred) (and Ipred Ipred) (or Ipred Ipred) (= Ix Ix) (> Ix Ix)))
  (Ix Int (Ic x5 x6 (- Ix) (+ Ix Ix) (ite Ipred Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var x Int)
(declare-var i Int)
(declare-var p Int)
(declare-var b Bool)
(declare-var b0 Bool)
(constraint (or (not (> x i)) (= (or (= x p) (or b b0)) (c0 x p))))
(check-synth)
