(set-logic LIA)
(synth-fun join ((x7 Int) (x8 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x7 x8 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun j2 ((x9 Int) (x10 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x9 x10 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var i5 Int)
(declare-var i6 Int)
(constraint (= p (join p 0)))
(constraint (= (+ p i5) (join p (j2 i5 0))))
(constraint (= (+ p (+ i5 i6)) (join p (j2 i5 (j2 i6 0)))))
(check-synth)
