(set-logic DTLIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(define-fun min ((x Int) (y Int)) Int (ite (<= x y) x y))
(synth-fun odot1 ((x5 (Tuple Int Int)) (x6 (Tuple Int Int))) Int ((Ix Int) (Ic Int))
 ((Ix Int
   (Ic ((_ tupSel 0) x5) ((_ tupSel 1) x5) ((_ tupSel 0) x6) ((_ tupSel 1) x6) 
    (- Ix) (+ Ix Ix) (min Ix Ix) (max Ix Ix)))
  (Ic Int ((Constant Int)))))
(declare-var p5 Int)
(declare-var p6 Int)
(declare-var i Int)
(declare-var i0 Int)
(constraint
 (or (not (<= i i0))
  (= (min (min i0 (max p6 i)) (max p5 (min p6 i)))
   (odot1 (mkTuple (min p5 p6) (max p5 p6)) (mkTuple i i0)))))
(check-synth)
