(set-logic DTLIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(define-fun min ((x Int) (y Int)) Int (ite (<= x y) x y))
(synth-fun join0 ((x9 Int) (x10 (Tuple Int Int)) (x11 (Tuple Int Int))) Int 
 ((Ix Int) (Ic Int))
 ((Ix Int
   (Ic x9 ((_ tupSel 0) x10) ((_ tupSel 1) x10) ((_ tupSel 0) x11) ((_ tupSel 1) x11) 
    (- Ix) (+ Ix Ix) (min Ix Ix) (max Ix Ix)))
  (Ic Int ((Constant Int)))))
(declare-var p0 Int)
(declare-var p3 Int)
(declare-var p7 Int)
(declare-var p8 Int)
(declare-var i Int)
(declare-var i3 Int)
(constraint (= (min (min p0 p3) p7) (join0 p0 (mkTuple p3 p3) (mkTuple p7 p7))))
(constraint
 (= (min (min (min (min p0 p3) p8) i) i3)
  (join0 p0 (mkTuple p3 p3) (mkTuple (min (min p8 i) i3) (max (max p8 i) i3)))))
(check-synth)
