(set-logic LIA)
(synth-fun sub1 ((x19 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x19 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun add1 ((x20 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x20 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun add ((x21 Int) (x22 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x21 x22 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun c0 () Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(constraint (= 0 (add c0 c0)))
(constraint (= 1 (add (add1 c0) c0)))
(constraint (= 1 (add c0 (add1 c0))))
(constraint (= (- 1) (add c0 (sub1 c0))))
(constraint (= 2 (add c0 (add1 (add1 c0)))))
(constraint (= 0 (add c0 (sub1 (add1 c0)))))
(check-synth)
