(set-logic DTLIA)
(define-fun min ((x Int) (y Int)) Int (ite (<= x y) x y))
(synth-fun odot0 ((x1 (Tuple Int Int)) (x2 (Tuple Int Int))) Int ((Ix Int) (Ic Int))
 ((Ix Int
   (Ic ((_ tupSel 0) x1) ((_ tupSel 1) x1) ((_ tupSel 0) x2) ((_ tupSel 1) x2) 
    (- Ix) (+ Ix Ix) (min Ix Ix)))
  (Ic Int ((Constant Int)))))
(declare-var p4 Int)
(declare-var i Int)
(declare-var i0 Int)
(constraint (= (min i p4) (odot0 (mkTuple p4 1) (mkTuple i i0))))
(check-synth)
