(set-logic DTLIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(define-fun min ((x Int) (y Int)) Int (ite (<= x y) x y))
(synth-fun join1 ((x12 Int) (x13 (Tuple Int Int)) (x14 (Tuple Int Int))) Int 
 ((Ix Int) (Ic Int))
 ((Ix Int
   (Ic x12 ((_ tupSel 0) x13) ((_ tupSel 1) x13) ((_ tupSel 0) x14) ((_ tupSel 1) x14) 
    (- Ix) (+ Ix Ix) (min Ix Ix) (max Ix Ix)))
  (Ic Int ((Constant Int)))))
(declare-var p0 Int)
(declare-var p3 Int)
(declare-var p7 Int)
(declare-var p8 Int)
(declare-var i Int)
(declare-var i3 Int)
(constraint (= (max (max p0 p3) p7) (join1 p0 (mkTuple p3 p3) (mkTuple p7 p7))))
(constraint
 (= (max (max (max (max p0 p3) p8) i) i3)
  (join1 p0 (mkTuple p3 p3) (mkTuple (min (min p8 i) i3) (max (max p8 i) i3)))))
(check-synth)
