(set-logic NIA)
(synth-fun odot ((x0 Int) (x1 Int)) Int ((Ix Int) (Ic Int) (Ipred Bool))
 ((Ix Int (Ic x0 x1 (- Ix) (+ Ix Ix) (ite Ipred Ix Ix))) (Ic Int ((Constant Int)))
  (Ipred Bool ((= Ix Ix) (> Ix Ix) (not Ipred) (and Ipred Ipred) (or Ipred Ipred)))))
(declare-var p4 Int)
(declare-var i Int)
(constraint (= i (odot 0 i)))
(constraint (= (+ (ite (= (mod p4 2) 0) p4 0) i) (odot (+ (ite (= (mod p4 2) 0) p4 0) 0) i)))
(check-synth)
