(set-logic LIA)
(synth-fun sub1 ((x15 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x15 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun add1 ((x16 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x16 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun add ((x17 Int) (x18 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x17 x18 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun c0 () Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(constraint (= 0 (add c0 c0)))
(constraint (= 1 (add (add1 c0) c0)))
(constraint (= 1 (add c0 (add1 c0))))
(constraint (= (- 1) (add c0 (sub1 c0))))
(constraint (= 2 (add c0 (add1 (add1 c0)))))
(check-synth)
