(set-logic DTLIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(synth-fun oplus0 ((x3 (Tuple Int Int)) (x4 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic ((_ tupSel 0) x3) ((_ tupSel 1) x3) x4 (- Ix) (+ Ix Ix) (max Ix Ix)))
  (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var p1 Int)
(constraint (= p (oplus0 (mkTuple 0 0) p)))
(constraint (= (+ p1 p) (oplus0 (mkTuple p (max 0 p)) p1)))
(check-synth)
