(set-logic LIA)
(synth-fun int_base () Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun s00 ((x6 Int) (x7 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x6 x7 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun s01 ((x8 Int) (x9 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x8 x9 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var i0 Int)
(constraint (or (not true) (= 1 (s00 i0 int_base))))
(constraint (or (not true) (= i0 (s01 i0 int_base))))
(check-synth)
