(set-logic DTLIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(synth-fun join1 ((x3 (Tuple Int Int)) (x4 (Tuple Int Int))) Int ((Ix Int) (Ic Int))
 ((Ix Int
   (Ic ((_ tupSel 0) x3) ((_ tupSel 1) x3) ((_ tupSel 0) x4) ((_ tupSel 1) x4) 
    (- Ix) (+ Ix Ix) (max Ix Ix)))
  (Ic Int ((Constant Int)))))
(declare-var p4 Int)
(declare-var i Int)
(declare-var i0 Int)
(constraint (or (not (and (>= i 0) (>= i i0))) (= i0 (join1 (mkTuple 0 0) (mkTuple i i0)))))
(constraint
 (or (not (and (>= i 0) (>= i i0)))
  (= (+ i0 p4) (join1 (mkTuple (max 0 (+ 0 p4)) (+ 0 p4)) (mkTuple i i0)))))
(check-synth)
