(set-logic LIA)
(synth-fun xi_2 ((x3 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x3 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var x Int)
(declare-var i Int)
(declare-var i1 Int)
(declare-var i2 Int)
(constraint (or (not (and (and (>= i1 0) (>= i2 0)) (not (< i x)))) (= (+ i1 i2) (xi_2 i1))))
(check-synth)
