(set-logic NIA)
(synth-fun c1 () Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var i3 Int)
(declare-var i4 Int)
(constraint
 (or (not (and (and (>= i3 0) (>= i4 0)) (or (not (and (>= i3 0) (>= i4 0))) (= i3 0))))
  (= (+ (+ (mod p 2) i3) i4) c1)))
(check-synth)
