(set-logic DTLIA)
(synth-fun odot1 ((x3 (Tuple Int Int)) (x4 (Tuple Int Int))) Int ((Ix Int) (Ic Int) (Ipred Bool))
 ((Ix Int
   (Ic ((_ tupSel 0) x3) ((_ tupSel 1) x3) ((_ tupSel 0) x4) ((_ tupSel 1) x4) 
    (- Ix) (+ Ix Ix) (ite Ipred Ix Ix)))
  (Ic Int ((Constant Int)))
  (Ipred Bool ((= Ix Ix) (> Ix Ix) (not Ipred) (and Ipred Ipred) (or Ipred Ipred)))))
(declare-var p4 Int)
(declare-var i Int)
(declare-var i0 Int)
(constraint (= (ite (< p4 i) 1 (+ i0 (ite (= p4 i) 1 0))) (odot1 (mkTuple p4 1) (mkTuple i i0))))
(check-synth)
