(set-logic LIA)
(synth-fun odot ((x1 Bool) (x2 Bool)) Bool ((Ipred Bool))
 ((Ipred Bool (x1 x2 (not Ipred) (and Ipred Ipred) (or Ipred Ipred)))))
(declare-var x Int)
(declare-var p4 Int)
(declare-var b Bool)
(constraint (= b (odot false b)))
(constraint (= (or (= x p4) b) (odot (or (= x p4) false) b)))
(check-synth)
