(set-logic LIA)
(synth-fun join ((x3 Int) (x4 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x3 x4 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun j2 ((x5 Int) (x6 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x5 x6 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var i0 Int)
(constraint (= p (join p 0)))
(constraint (= (+ p i0) (join p (j2 i0 0))))
(check-synth)
