(set-logic DTLIA)
(synth-fun odot ((x (Tuple Int Int Bool)) (x0 (Tuple Int Int Bool))) 
 (Tuple Int Int Bool) ((Tr (Tuple Int Int Bool)) (Ix Int) (Ic Int) (Ipred Bool))
 ((Tr (Tuple Int Int Bool) ((mkTuple Ix Ix Ipred)))
  (Ix Int
   (Ic ((_ tupSel 0) x) ((_ tupSel 1) x) ((_ tupSel 0) x0) ((_ tupSel 1) x0) 
    (- Ix) (+ Ix Ix) (ite Ipred Ix Ix)))
  (Ic Int ((Constant Int)))
  (Ipred Bool
   (((_ tupSel 2) x) ((_ tupSel 2) x0) (= Ix Ix) (> Ix Ix) (not Ipred) 
    (and Ipred Ipred) (or Ipred Ipred)))))
(declare-var p4 Int)
(declare-var i Int)
(declare-var i0 Int)
(declare-var b Bool)
(constraint (= (mkTuple p4 i0 (and b (< p4 i))) (odot (mkTuple p4 p4 true) (mkTuple i i0 b))))
(check-synth)
