(set-logic LIA)
(synth-fun odot ((x1 Int) (x2 Int) (x3 Int)) Int ((Ix Int) (Ic Int) (Ipred Bool))
 ((Ix Int (Ic x1 x2 x3 (- Ix) (+ Ix Ix) (ite Ipred Ix Ix))) (Ic Int ((Constant Int)))
  (Ipred Bool ((= Ix Ix) (> Ix Ix) (not Ipred) (and Ipred Ipred) (or Ipred Ipred)))))
(declare-var c Int)
(declare-var p4 Int)
(declare-var i Int)
(constraint (= i (odot c 0 i)))
(constraint (= (+ (ite (> p4 c) p4 0) i) (odot c (+ (ite (> p4 c) p4 0) 0) i)))
(check-synth)
