(set-logic LIA)
(synth-fun oplus ((x Int) (x0 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x x0 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(constraint (= p (oplus 0 p)))
(check-synth)
