(set-logic LIA)
(synth-fun join ((x2 Int) (x3 Int) (x4 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x2 x3 x4 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var p2 Int)
(declare-var i2 Int)
(constraint (= (+ i2 p) (join p i2 0)))
(constraint (= (+ (+ i2 p) p2) (join p i2 (+ 0 p2))))
(check-synth)
