(set-logic LIA)
(synth-fun sub1 ((x3 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x3 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(constraint (= (- 1) (sub1 0)))
(constraint (= 0 (sub1 (+ 1 0))))
(check-synth)
