(set-logic LIA)
(synth-fun join ((x Int) (x0 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x x0 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(constraint (= p (join p 1)))
(check-synth)
