(set-logic DTLIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(synth-fun odot0 ((x1 (Tuple Int Int)) (x2 (Tuple Int Int))) Int ((Ix Int) (Ic Int))
 ((Ix Int
   (Ic ((_ tupSel 0) x1) ((_ tupSel 1) x1) ((_ tupSel 0) x2) ((_ tupSel 1) x2) 
    (- Ix) (+ Ix Ix) (max Ix Ix)))
  (Ic Int ((Constant Int)))))
(declare-var i Int)
(declare-var i0 Int)
(declare-var i1 Int)
(constraint (or (not (>= i0 0)) (= i0 (odot0 (mkTuple 0 0) (mkTuple i0 i1)))))
(constraint
 (or (not (>= i0 0))
  (= (max (+ i0 i) 0) (odot0 (mkTuple (max (+ 0 i) 0) (+ 0 i)) (mkTuple i0 i1)))))
(check-synth)
