(set-logic LIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(synth-fun xi_1 ((x3 Int) (x4 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x3 x4 (- Ix) (+ Ix Ix) (max Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var i0 Int)
(declare-var i813 Int)
(constraint (or (not (= i0 (max i0 p))) (= (max i0 (max p i813)) (xi_1 p i0))))
(check-synth)
