(set-logic LIA)
(synth-fun gt_case ((x5 Bool) (x6 Bool)) Bool ((Ipred Bool))
 ((Ipred Bool (x5 x6 (not Ipred) (and Ipred Ipred) (or Ipred Ipred)))))
(declare-var lo Int)
(declare-var hi Int)
(declare-var i Int)
(declare-var b Bool)
(declare-var b0 Bool)
(constraint (or (not (>= i hi)) (= (or (and (< lo i) (< i hi)) (or b b0)) (gt_case b b0))))
(check-synth)
