(set-logic LIA)
(synth-fun sub1 ((x7 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x7 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun add1 ((x8 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x8 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun add ((x9 Int) (x10 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x9 x10 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun c0 () Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(constraint (= 0 (add c0 c0)))
(constraint (= 1 (add c0 (add1 c0))))
(constraint (= (- 1) (add c0 (sub1 c0))))
(check-synth)
