(set-logic LIA)
(synth-fun op ((x3 Int) (x4 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x3 x4 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun s0 () Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun join ((x5 Int) (x6 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x5 x6 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var i Int)
(declare-var i4 Int)
(constraint (= i4 (join s0 i4)))
(constraint (= (+ i i4) (join (op i s0) i4)))
(check-synth)
