(set-logic DTLIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(define-fun min ((x Int) (y Int)) Int (ite (<= x y) x y))
(synth-fun odot0 ((x3 (Tuple Int Int)) (x4 (Tuple Int Int))) Int ((Ix Int) (Ic Int))
 ((Ix Int
   (Ic ((_ tupSel 0) x3) ((_ tupSel 1) x3) ((_ tupSel 0) x4) ((_ tupSel 1) x4) 
    (- Ix) (+ Ix Ix) (min Ix Ix) (max Ix Ix)))
  (Ic Int ((Constant Int)))))
(declare-var p5 Int)
(declare-var p6 Int)
(declare-var i Int)
(declare-var i0 Int)
(constraint
 (or (not (<= i i0))
  (= (min p5 (min p6 i)) (odot0 (mkTuple (min p5 p6) (max p5 p6)) (mkTuple i i0)))))
(check-synth)
