(set-logic LIA)
(synth-fun join ((x Int) (x0 Int) (x1 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x x0 x1 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var i Int)
(constraint (= (+ i p) (join p i 0)))
(check-synth)
