(set-logic LIA)
(synth-fun add1 ((x4 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x4 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun add ((x5 Int) (x6 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x5 x6 (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(synth-fun c0 () Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic (- Ix) (+ Ix Ix))) (Ic Int ((Constant Int)))))
(constraint (= 0 (add c0 c0)))
(constraint (= 1 (add c0 (add1 c0))))
(check-synth)
