(set-logic DTLIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(synth-fun oplus1 ((x5 (Tuple Int Int)) (x6 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic ((_ tupSel 0) x5) ((_ tupSel 1) x5) x6 (- Ix) (+ Ix Ix) (max Ix Ix)))
  (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var p1 Int)
(constraint (= (max p 0) (oplus1 (mkTuple 0 0) p)))
(constraint (= (max (+ p p1) (max p1 0)) (oplus1 (mkTuple p (max p 0)) p1)))
(check-synth)
