(set-logic LIA)
(define-fun max ((x Int) (y Int)) Int (ite (>= x y) x y))
(synth-fun join ((x3 Int)) Int ((Ix Int) (Ic Int))
 ((Ix Int (Ic x3 (- Ix) (+ Ix Ix) (max Ix Ix))) (Ic Int ((Constant Int)))))
(declare-var p Int)
(declare-var i15 Int)
(constraint (or (not (= p (max p i15))) (= (max p i15) (join p))))
(check-synth)
